### ISSUE TITLE
Biomes extend too far from cliff faces

### ISSUE THREAD

**Issue by lawrencedumarey** [Apollounknowndev/tectonic#70]
As the name suggests vanilla as well as modded structures sometimes spawn on top of water very close to the mainland. Im using terralith with tectonic as well as William Whyther overhauled overworld however that last one doest affect this issue. Its only terralith and Tectonic. Here is also a picture of the problem. 

![2023-11-12_22 43 02](https://github.com/Apollounknowndev/tectonic/assets/108006584/5ea71fb6-29d7-457b-b334-0bf37107ac2a)

Now this one isnt a vanilla structure but if you would like i could def find a seed and coords for you for a vanilla structure that does this!

PS thank you so much for your mod it is 100% the best terrain gen out there really mind boggling.
Sincirely,
Larry

**Comment by lawrencedumarey** [comment]
I was also using Terrablender in that instance, could it be this? I stopped using it and can't find any 'wrong' biomes that extend too far. Though might have been just luck, also on 1.20.1

**Comment by lawrencedumarey** [comment]
Aaaah nvm that wasnt it

**Comment by IDonutKnowYT** [comment]
This is happening to me as well...

**Comment by Reshy** [comment]
This is occurring to me as well.  Entire biomes will spawn in the ocean, thus causing buildings to spawn floating on water.
![image](https://github.com/Apollounknowndev/tectonic/assets/2096384/01f2f873-e9aa-458f-a3ae-48587ccac4bb)
![image](https://github.com/Apollounknowndev/tectonic/assets/2096384/e4cbbde6-ce61-475e-ab52-0d71b9d3fc78)

Also seems like the terrain doesn't generate correctly when using Wyther's or Better Nether.

**Comment by highlunlikely** [comment]
ive been building my mod list and testing and i suppose the main issue is incompatibility with structure mods that generate their own terrain underneath them, like towns and towers, moogs voyager structures, dungeons and taverns, etc. because even on land with Tectonic these structures that generate their own terrain can stick out very jarringly as they were made for vanilla terrain generation and i would imagine can even conflict slightly with vanilla terrain generation. i would think resolving the incompatibility with these kinds of structure mods isn't something in your control, but at least fixing this ocean biome spawn issue is the last step in making this the greatest terrain generation mod for Minecraft as its still bizarre using travelers titles, sailing through an open ocean and seeing random biomes like "forest" and "savannah" pop up, but I will still happily ditch those structure mods to use your mod and retain immersion. keep up the great work!

**Comment by Apollounknowndev** [comment]
Fixed in v2.2.1.

![image](https://github.com/Apollounknowndev/tectonic/assets/102649729/09db70d1-48ff-4d40-aded-0be5ef188f71)

**Comment by lawrencedumarey** [comment]
This issue saddly still persists when using william wythers overhauled overworld :'(

**Comment by Apollounknowndev** [comment]
That is specifically an issue with WWOO's compatibility mode, it does not have to do with Tectonic.

**Comment by lawrencedumarey** [comment]
I see, thank you! Is this a mode that i can turn off or is this a permanent thing from wwoo? Also your mod is zo amazing i literally cant play vanilla minecraft anymore haha

**Comment by Apollounknowndev** [comment]
It's a longstanding issue with WWOO's Terrablender-compatible mode, a precise cause hasn't been found yet and the mod has been mostly abandoned at this point.

**Comment by lawrencedumarey** [comment]
WWOO, been more than a year since last updated

**Comment by Reshy** [comment]
Asking since the original mod was split into Overhauled Overworld (changes existing biomes) and Expanded Ecosphere (adds biomes) which was updated in January.  Is it the former or the latter that's causing the issue?

**Comment by Apollounknowndev** [comment]
Expanded Ecosphere is causing the issues, but in-game it's still called Overhauled Overworld
